name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awscli --upgrade --user
        
    - name: Configure AWS credentials
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region your-aws-region
      
    - name: Package Lambda code
      run: |
        zip -r lambda.zip your-lambda-code-directory
        
    - name: Upload Lambda code to S3
      run: |
        aws s3 cp lambda.zip s3://your-s3-bucket/
        
    - name: Deploy to AWS CodeDeploy
      run: |
        aws deploy create-deployment --application-name your-application-name --deployment-group-name your-deployment-group-name --s3-location bucket=your-s3-bucket,key=lambda.zip,bundleType=zip
